spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        jpa:
            hibernate:
                ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
            show-sql: ${SPRING_JPA_SHOW_SQL}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://securetoken.google.com/noxshop-90b79
    firebase:
        credentials:
            path: /etc/secrets/firebase-service-account.json
    server:
        port: 8085